services:
  mysql:
    image: mysql:8
    container_name: api_django
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3308:3306"
    volumes:
      - mi_mysql_volumen_Django:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d

volumes:
  mi_mysql_volumen_Django: {}